nelmio_api_doc:
    models:
        names:
            - { alias: AllClients, type: App\Entity\Client, groups: [getClients]},
            - { alias: ClientDetails, type: App\Entity\Client, groups: [getSingleClient]}
            - { alias: AllPhones, type: App\Entity\Phone, groups: [getPhones]}
            - { alias: PhoneDetails, type: App\Entity\Phone, groups: [getSinglePhone]}
    documentation:
        info:
            title: BileMo
            description: Une API pour gérer vos clients et voir nos produits BileMo !
            version: 1.0.0
        paths:
            /api/login_check:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token
                    summary: Permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Crée un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: user@orange.fr
                        password:
                            type: string
                            default: password
                AddClient:
                    type: object
                    properties:
                        firstName:
                            type: string
                        lastName:
                            type: string
                        email:
                            type: string
                        phoneNumber:
                            type: string
                        address:
                            type: string
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        disable_default_routes: true